### ISSUE TITLE
给的链接打开后提示  404

### ISSUE THREAD

**Issue by Wangct23** [nibnait/algorithms#4]

**Comment by claudehang** [comment]
是的，全部404没有一个可以打开

**Comment by nibnait** [comment]
感谢关注。不好意思，目录结构做了些调整。
现已更新README文件。

算法篇已移至：https://github.com/nibnait/algorithms/blob/master/src/main/java/algorithm_practice/README.md
《剑指Offer》专题已移至：
https://github.com/nibnait/algorithms/blob/master/src/main/java/algorithm_practice/SwordOffer/README.md
